In [ ]:
# command for starting the kernel:
# python -m pip install ipykernel -> Run in TERMINAL
# python -m ipykernel install --user --name Student-Performance-EDA --display-name "Student-Performance-EDA (.venv)"
# At the top right corner -> Kernel selector -> Python Environements.... -> select the last one marked with a bright big star and has the path \* .venv\\Scripts\\python.exe
# Verify that the notebook is really using the .venv:
# import sys
# print(sys.executable)

In [2]:
import sys

In [3]:
print(sys.executable)

c:\PYTHON_PRACTICE\Student-Performance-EDA\.venv\Scripts\python.exe

In [3]:
# In terminal:
# pip install pandas     -> import pandas as pd   -> import numpy as np
# pip install matplotlib     -> import matplotlib.pyplot as plt
# pip install seaborn       -> import seaborn as sns
# pip install openpyxl -> for reading .xlsx files pandas needs this package

In [4]:
import pandas as pd

In [5]:
import numpy as np

In [6]:
import matplotlib.pyplot as plt

In [7]:
import seaborn as sns

In [8]:
df = pd.read_csv("enhanced_student_habits_performance_dataset.csv")

In [ ]:
# DATA EXPLORATION
df.head()

,student_id,age,gender,major,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,...,screen_time,study_environment,access_to_tutoring,family_income_range,parental_support_level,motivation_level,exam_anxiety_score,learning_style,time_management_score,exam_score
0,100000,26,Male,Computer Science,7.645367,3.0,0.1,Yes,70.3,6.2,...,10.9,Co-Learning Group,Yes,High,9,7,8,Reading,3.0,100
1,100001,28,Male,Arts,5.700000,0.5,0.4,No,88.4,7.2,...,8.3,Co-Learning Group,Yes,Low,7,2,10,Reading,6.0,99
2,100002,17,Male,Arts,2.400000,4.2,0.7,No,82.1,9.2,...,8.0,Library,Yes,High,3,9,6,Kinesthetic,7.6,98
3,100003,27,Other,Psychology,3.400000,4.6,2.3,Yes,79.3,4.2,...,11.7,Co-Learning Group,Yes,Low,5,3,10,Reading,3.2,100
4,100004,25,Female,Business,4.700000,0.8,2.7,Yes,62.9,6.5,...,9.4,Quiet Room,Yes,Medium,9,1,10,Reading,7.1,98

In [10]:
df.describe

<bound method NDFrame.describe of        student_id  age  gender             major  study_hours_per_day  \
0          100000   26    Male  Computer Science             7.645367
1          100001   28    Male              Arts             5.700000
2          100002   17    Male              Arts             2.400000
3          100003   27   Other        Psychology             3.400000
4          100004   25  Female          Business             4.700000
...           ...  ...     ...               ...                  ...
79995      179995   16    Male       Engineering             3.700000
79996      179996   16  Female          Business             1.200000
79997      179997   26  Female              Arts             4.100000
79998      179998   23   Other           Biology             3.800000
79999      179999   25   Other       Engineering             3.000000

       social_media_hours  netflix_hours part_time_job  attendance_percentage  \
0                     3.0            0.1           Yes                   70.3
1                     0.5            0.4            No                   88.4
2                     4.2            0.7            No                   82.1
3                     4.6            2.3           Yes                   79.3
4                     0.8            2.7           Yes                   62.9
...                   ...            ...           ...                    ...
79995                 2.1            1.0           Yes                   80.8
79996                 0.4            2.9            No                   99.5
79997                 1.6            1.6           Yes                   46.1
79998                 0.6            3.5           Yes                   58.7
79999                 4.5            3.4           Yes                   97.7

       sleep_hours  ... screen_time  study_environment access_to_tutoring  \
0              6.2  ...        10.9  Co-Learning Group                Yes
1              7.2  ...         8.3  Co-Learning Group                Yes
2              9.2  ...         8.0            Library                Yes
3              4.2  ...        11.7  Co-Learning Group                Yes
4              6.5  ...         9.4         Quiet Room                Yes
...            ...  ...         ...                ...                ...
79995          6.1  ...         8.3            Library                 No
79996          4.1  ...         4.7  Co-Learning Group                 No
79997          8.3  ...         7.5               Dorm                 No
79998          5.8  ...         9.3         Quiet Room                Yes
79999          5.3  ...        12.2  Co-Learning Group                Yes

      family_income_range  parental_support_level motivation_level  \
0                    High                       9                7
1                     Low                       7                2
2                    High                       3                9
3                     Low                       5                3
4                  Medium                       9                1
...                   ...                     ...              ...
79995                 Low                       1                4
79996                 Low                       3                2
79997              Medium                       7                1
79998                 Low                       2                8
79999              Medium                       1                8

       exam_anxiety_score  learning_style  time_management_score exam_score
0                       8         Reading                    3.0        100
1                      10         Reading                    6.0         99
2                       6     Kinesthetic                    7.6         98
3                      10         Reading                    3.2        100
4                      10         Reading                    7.1         98
...                   ...             ...                    ...        ...
79995                  10        Auditory                    5.3         88
79996                  10     Kinesthetic                    6.8         52
79997                  10          Visual                    1.3         89
79998                   7     Kinesthetic                    3.7         96
79999                   7         Reading                    6.7        100

[80000 rows x 31 columns]>

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 31 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   student_id                     80000 non-null  int64
 1   age                            80000 non-null  int64
 2   gender                         80000 non-null  str
 3   major                          80000 non-null  str
 4   study_hours_per_day            80000 non-null  float64
 5   social_media_hours             80000 non-null  float64
 6   netflix_hours                  80000 non-null  float64
 7   part_time_job                  80000 non-null  str
 8   attendance_percentage          80000 non-null  float64
 9   sleep_hours                    80000 non-null  float64
 10  diet_quality                   80000 non-null  str
 11  exercise_frequency             80000 non-null  int64
 12  parental_education_level       80000 non-null  str
 13  internet_quality               80000 non-null  str
 14  mental_health_rating           80000 non-null  float64
 15  extracurricular_participation  80000 non-null  str
 16  previous_gpa                   80000 non-null  float64
 17  semester                       80000 non-null  int64
 18  stress_level                   80000 non-null  float64
 19  dropout_risk                   80000 non-null  str
 20  social_activity                80000 non-null  int64
 21  screen_time                    80000 non-null  float64
 22  study_environment              80000 non-null  str
 23  access_to_tutoring             80000 non-null  str
 24  family_income_range            80000 non-null  str
 25  parental_support_level         80000 non-null  int64
 26  motivation_level               80000 non-null  int64
 27  exam_anxiety_score             80000 non-null  int64
 28  learning_style                 80000 non-null  str
 29  time_management_score          80000 non-null  float64
 30  exam_score                     80000 non-null  int64
dtypes: float64(10), int64(9), str(12)
memory usage: 18.9 MB

In [12]:
df.shape

(80000, 31)

In [ ]:
# DATA CLEANING -> CHECKING MISSING VALUES
df.isnull().sum()

student_id                       0
age                              0
gender                           0
major                            0
study_hours_per_day              0
social_media_hours               0
netflix_hours                    0
part_time_job                    0
attendance_percentage            0
sleep_hours                      0
diet_quality                     0
exercise_frequency               0
parental_education_level         0
internet_quality                 0
mental_health_rating             0
extracurricular_participation    0
previous_gpa                     0
semester                         0
stress_level                     0
dropout_risk                     0
social_activity                  0
screen_time                      0
study_environment                0
access_to_tutoring               0
family_income_range              0
parental_support_level           0
motivation_level                 0
exam_anxiety_score               0
learning_style                   0
time_management_score            0
exam_score                       0
dtype: int64

In [ ]:
# DATA CLEANING -> CHECKING DUPLICATE VALUES:
df.duplicated().sum()

np.int64(0)

In [ ]:
# There are no duplicate values in the dataset

In [16]:
df.head()

,student_id,age,gender,major,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,...,screen_time,study_environment,access_to_tutoring,family_income_range,parental_support_level,motivation_level,exam_anxiety_score,learning_style,time_management_score,exam_score
0,100000,26,Male,Computer Science,7.645367,3.0,0.1,Yes,70.3,6.2,...,10.9,Co-Learning Group,Yes,High,9,7,8,Reading,3.0,100
1,100001,28,Male,Arts,5.700000,0.5,0.4,No,88.4,7.2,...,8.3,Co-Learning Group,Yes,Low,7,2,10,Reading,6.0,99
2,100002,17,Male,Arts,2.400000,4.2,0.7,No,82.1,9.2,...,8.0,Library,Yes,High,3,9,6,Kinesthetic,7.6,98
3,100003,27,Other,Psychology,3.400000,4.6,2.3,Yes,79.3,4.2,...,11.7,Co-Learning Group,Yes,Low,5,3,10,Reading,3.2,100
4,100004,25,Female,Business,4.700000,0.8,2.7,Yes,62.9,6.5,...,9.4,Quiet Room,Yes,Medium,9,1,10,Reading,7.1,98

In [ ]:
# Q Checking wether the numerical values are within reasonable rangles -> meaning the values are valid 

# 1.  Check any unusual study hour values
df["study_hours_per_day"].describe()

# ANS -> no suspicious values found

count    80000.000000
mean         4.174388
std          2.004135
min          0.000000
25%          2.800000
50%          4.125624
75%          5.500000
max         12.000000
Name: study_hours_per_day, dtype: float64

In [ ]:
# 2. Check any unusual sleep hour values
df["sleep_hours"].describe()
# ANS -> no suspicious values found

count    80000.000000
mean         7.017418
std          1.467377
min          4.000000
25%          6.000000
50%          7.000000
75%          8.000000
max         12.000000
Name: sleep_hours, dtype: float64

In [ ]:
# 3. Check any unusual attendance percentages
df["attendance_percentage"].describe()
# ANS -> no suspicious values found

count    80000.000000
mean        69.967884
std         17.333015
min         40.000000
25%         55.000000
50%         69.900000
75%         84.900000
max        100.000000
Name: attendance_percentage, dtype: float64